name: Junit CI Tests

on: [push, pull_request]

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up custom JDK
      uses: actions/setup-java@v2
      with:
        java-version: '22.0.1'
        distribution: 'adopt'

    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots --no-transfer-progress clean install

    - name: Run tests with Maven
      run: mvn test
